Metrics/AbcSize:
  Max: 50

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/BlockLength:
  Max: 60

Metrics/MethodLength:
  Max: 40

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/Semicolon:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 20
